services:
  spark:
    version: 3.2.1
    download-source: "https://archive.apache.org/dist/spark/spark-3.2.1/"
  hdfs:
    version: 3.2.2
    download-source: "https://archive.apache.org/dist/hadoop/core/hadoop-3.2.2/"
provider: ec2
providers:
  ec2:
    key-name: <ec2-key-pair>
    identity-file: /your/path/to/ec2-key-pair-pem-file/<ec2-key-pair>.pem
    instance-type: c5d.9xlarge
    region: us-east-1
    ami: ami-05fa00d4c63e32376
    user: ec2-user
    instance-profile-name: EMR_EC2_DefaultRole
    min-root-ebs-size-gb: 20
    tenancy: default  # default | dedicated
    ebs-optimized: yes  # yes | no
    instance-initiated-shutdown-behavior: terminate  # terminate | stop

launch:
  num-slaves: 6
  install-hdfs: True
  install-spark: True
  java-version: 8

debug: false
